Move to the binding-tools-for-swift-reflector repository for the reflector.
This also means we have to adjust the reflector hash.

diff --git a/jenkins/azure-pipelines.yml b/jenkins/azure-pipelines.yml
--- a/jenkins/azure-pipelines.yml
+++ b/jenkins/azure-pipelines.yml
@@ -5,55 +5,169 @@
 trigger:
 - '*'
 
-pool:
-  vmImage: 'macOS-10.14'
+jobs:
+- job: ContinuousIntegration
+  timeoutInMinutes: 720 # 12 hours (but 6 is max on hosted agents)
+  pool:
+    vmImage: 'macOS-10.14'
 
-steps:
-- script: |
-    set +e # we don't care about errors here
-    set -x
-    pwd
-    env | sort
-    ls -la /Applications
-    system_profiler SPHardwareDataType
-    curl -s https://support-sp.apple.com/sp/product?cc=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' | cut -c 9-) | sed 's|.*<configCode>\(.*\)</configCode>.*|\1|'
-    sysctl -a | grep cpu
-    exit 0 # make sure we don't return an error code if the last command failed
-  displayName: 'Environment info'
+  steps:
+  - script: |
+      set +e # we don't care about errors here
+      set -x
+      pwd
+      env | sort
+      ls -la /Applications
+      system_profiler SPHardwareDataType
+      curl -s https://support-sp.apple.com/sp/product?cc=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' | cut -c 9-) | sed 's|.*<configCode>\(.*\)</configCode>.*|\1|'
+      sysctl -a | grep cpu
+      exit 0 # make sure we don't return an error code if the last command failed
+    displayName: 'Environment info'
 
-- script: |
-    set -e
-    set -x
-    ./jenkins/provision-deps.sh
-  displayName: 'Provision dependencies'
+  - script: |
+      set -e
+      set -x
+      ./jenkins/provision-deps.sh
+    displayName: 'Provision dependencies'
 
-- script: |
-    set -e
-    set -x
-    ./jenkins/build-swift.sh --publish
-  displayName: 'Build Swift'
+  - script: |
+      set -e
+      set -x
+      ./jenkins/build-swift.sh --publish
+      mkdir -p ../toolchain
+      if test -f Pack-Man/SwiftToolchain-*.zip; then
+        cp -c Pack-Man/SwiftToolchain-*.zip ../toolchain
+        echo "##vso[task.setvariable variable=uploadtoolchain;isOutput=true]1"
+      else
+        echo "##vso[task.setvariable variable=uploadtoolchain;isOutput=true]0"
+      fi
+    displayName: 'Build Swift'
+    name: BuildSwift
 
-- script: |
-    set -e
-    set -x
-    ./jenkins/build.sh
-  displayName: 'Build'
+  # This will upload the updated toolchain zip (if any) to Azure Devops
+  # A later job further down will then publish the toolchain to Azure Blob Storage.
+  # This is a two-step process because the task that can publish to Azure Blob Storage only works on Windows :/
+  - task: PublishBuildArtifacts@1
+    displayName: 'Upload Swift Toolchain'
+    inputs:
+      PathtoPublish: '../toolchain'
+      ArtifactName: 'toolchain'
+      publishLocation: 'Container'
 
-- script: |
-    set -e
-    set -x
-    ./jenkins/build-package.sh
-    ls -la ../package || true
-  displayName: 'Package'
+  - script: |
+      set -e
+      set -x
+      ./jenkins/build.sh
+    displayName: 'Build'
 
-- task: PublishBuildArtifacts@1
-  inputs:
-    PathtoPublish: '../package'
-    ArtifactName: 'drop'
-    publishLocation: 'Container'
+  - script: |
+      set -e
+      set -x
+      ./jenkins/build-package.sh
+      ls -la ../package || true
+    displayName: 'Package'
 
-- script: |
-    set -e
-    set -x
-    ./jenkins/run-tests.sh
-  displayName: 'Run tests'
+  # This will upload the packages to Azure Devops
+  # A later job further down will then publish the package to Azure Blob Storage.
+  # This is a two-step process because the task that can publish to Azure Blob Storage only works on Windows :/
+  - task: PublishBuildArtifacts@1
+    displayName: 'Upload Packages'
+    inputs:
+      PathtoPublish: '../package'
+      ArtifactName: 'drop'
+      publishLocation: 'Container'
+
+  - script: |
+      set -e
+      set -x
+      ./jenkins/run-tests.sh
+    displayName: 'Run tests'
+
+- job: UploadToolchain
+  dependsOn: ContinuousIntegration
+  condition: eq(dependencies.ContinuousIntegration.outputs['BuildSwift.uploadtoolchain'], '1')
+  pool:
+    vmImage: windows-latest
+
+  steps:
+  - task: DownloadPipelineArtifact@2
+    inputs:
+      source: current
+      artifact: toolchain
+      path: 'toolchain'
+
+  - task: AzureFileCopy@2
+    displayName: 'Publish toolchain to Azure'
+    inputs:
+      SourcePath: 'toolchain'
+      azureSubscription: BOSStorageMirror
+      Destination: AzureBlob
+      storage: bosstoragemirror
+      ContainerName: wrench
+      BlobPrefix: 'binding-tools-for-swift/toolchain'
+      outputStorageUri: ToolchainUrl
+      outputStorageContainerSasToken: ToolchainSasToken
+
+  - bash: |
+      set -e
+      set -x
+      ZIPS=(toolchain/*.zip)
+      if (( ${#ZIPS[@]} == 1 )); then
+        if test -f "${ZIPS[0]}"; then
+          FILE=${ZIPS[0]}
+        else
+          echo "Could not find any zip files to upload"
+          exit 1
+        fi
+      elif (( ${#ZIPS[@]} > 1 )); then
+        echo "More than one zip file!"
+        exit 1
+      fi
+      FILENAME="$(basename "$FILE")"
+      TARGET_URL="https://bosstoragemirror.blob.core.windows.net/wrench/binding-tools-for-swift/toolchains/$FILENAME"
+      ./jenkins/add-commit-status.sh --token=$(github-pat) --hash=$BUILD_SOURCEVERSION --state=success --target-url=$TARGET_URL "--description=$FILENAME" --context=Toolchain-Binding-Tools-For-Swift
+    displayName: 'Add Toolchain as GitHub Status'
+
+- job: UploadPackages
+  dependsOn: ContinuousIntegration
+  pool:
+    vmImage: windows-latest
+
+  steps:
+  - task: DownloadPipelineArtifact@2
+    inputs:
+      source: current
+      artifact: drop
+      path: 'drop'
+
+  - task: AzureFileCopy@2
+    displayName: 'Publish package to Azure'
+    inputs:
+      SourcePath: 'drop'
+      azureSubscription: BOSStorageMirror
+      Destination: AzureBlob
+      storage: bosstoragemirror
+      ContainerName: wrench
+      BlobPrefix: 'binding-tools-for-swift/$(Build.SourceBranchName)/$(Build.SourceVersion)/$(Build.BuildId)'
+      outputStorageUri: PackageUrl
+      outputStorageContainerSasToken: PackageSasToken
+
+  - bash: |
+      set -e
+      set -x
+      ZIPS=(drop/*.zip)
+      if (( ${#ZIPS[@]} == 1 )); then
+        if test -f "${ZIPS[0]}"; then
+          FILE=${ZIPS[0]}
+        else
+          echo "Could not find any zip files"
+          exit 1
+        fi
+      elif (( ${#ZIPS[@]} > 1 )); then
+        echo "More than one zip file!"
+        exit 1
+      fi
+      FILENAME="$(basename "$FILE")"
+      TARGET_URL="https://bosstoragemirror.blob.core.windows.net/wrench/binding-tools-for-swift/$BUILD_SOURCEBRANCHNAME/$BUILD_SOURCEVERSION/$BUILD_BUILDID/$FILENAME"
+      ./jenkins/add-commit-status.sh --token=$(github-pat) --hash=$BUILD_SOURCEVERSION --azdo-state=$AGENT_JOBSTATUS --target-url=$TARGET_URL "--description=$FILENAME" --context=PKG-Binding-Tools-For-Swift
+    displayName: 'Add Packages as GitHub Status'
